_target_: models.fashion_mnist.FashionMNISTLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: models.components.cnn.CNN
  input_channels: 1
  input_size: [28, 28]
  dropout: 0.5
  num_classes: 10

compile: false
