# @package _global_

defaults:
  - override /hydra/sweeper: optuna

target_metric: val/acc_best

hydra:
  mode: MULTIRUN

  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    storage: sqlite:///${paths.log_dir}/optuna.db
    study_name: ${task_name}

    n_jobs: 5

    direction: maximize

    n_trials: 30

    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 42
      n_startup_trials: 10

    params:
      model.optimizer.lr: interval(0.0001, 0.1)
      model.net.dropout: range(0.0, 0.9, step=0.1)
