model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${paths.output_dir}/checkpoints
  filename: epoch_{epoch:03d}
  monitor: val/loss
  verbose: False
  save_last: True
  save_top_k: 1
  mode: min
  auto_insert_metric_name: False
  save_weights_only: False
  every_n_train_steps: null
  train_time_interval: null
  every_n_epochs: null
  save_on_train_epoch_end: null
