# @package _global_

task_name: debug

callbacks: null
logger: null

ignore_warnings: False

hydra:
  job_logging:
    root:
      level: DEBUG

  verbose: True

trainer:
  max_epochs: 1
  accelerator: cpu
  devices: 1
  detect_anomaly: True
  fast_dev_run: true

data:
  num_workers: 0
  pin_memory: False
  persistent_workers: False
