name: Format on push

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

env:
  CREATE_PR: false

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Run pre-commit
        id: pre-commit
        uses: pre-commit/action@v2.0.3

      - name: Create PR if needed
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "style: Apply formatter auto-fixes"
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          delete-branch: true
          sign-commits: true
          title: Apply formatter auto-fixes
          body: This PR was created by the [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub Action and includes fixes automatically formatted by [pre-commit](https://github.com/pre-commit/pre-commit).
          labels: |
            style
            automated pr
        if: failure() && steps.pre-commit.outcome == 'failure' && env.CREATE_PR == 'true'
